Regenerator improvements
wwood/singlem pull request #86
Opened 2021-09-12 23:49 UTC by AroneyS

Change regenerator to take SingleM package as input and output updated SingleM package with sequences and taxonomy replaced by updated versions. GraftM package HMMs are unchanged.

Arguments: 
input_singlem_package, output_singlem_package: 
input_sequences, input_taxonomy: new bacteria/archaea sequences and taxonomy
euk_sequences, euk_taxonomy: candidate eukaryotic sequences and taxonomy (graftM graft used to select matches)
window_position: optionally adjust the window position of the package
sequence_prefix: optionally add a prefix to each sequence ID (e.g. package name)
min_aligned_percent: optionally define GraftM create sequence inclusion parameter

2021-09-13 00:28 UTC, AroneyS commented
I regenerated S2.1 with this but the output S3.1 is not finding the same sequences. I'll do more testing to figure out what is going on.

2021-09-17 02:43 UTC, AroneyS commented
Creating and using a regenerated S3 metapackage now works.

2021-09-23 02:13 UTC, wwood requested changes
Hey just the tiniest thing. Thanks for this.

2021-09-23 02:13 UTC, wwood commented on singlem/package_creator.py
> +            taxonomy_hash_tf.close()
How come close here instead of just replacing `taxonomy_hash_tf.flush()` above?

2021-09-23 23:58 UTC, AroneyS commented on singlem/package_creator.py
> +            taxonomy_hash_tf.close()
Good point

2021-09-24 00:17 UTC, merged